### ISSUE TITLE
xformers use

### ISSUE THREAD

**Issue by wangfei0903** [Shilin-LU/TF-ICON#27]
Hello author, thank you very much for publishing such an excellent paper. I would like to inquire where you started xforms?

**Comment by wangfei0903** [comment]
Because I need about 30 seconds to perform a fusion, but you said it only takes 3 or 4 seconds

**Comment by wangfei0903** [comment]
Because I need about 30 seconds to perform a fusion by a100, but you said it only takes 8 seconds

**Comment by Shilin-LU** [comment]
Thank you for your interest. This code does not use the xformer. The running time depends on the size of the composition area, so larger cases may take longer to process.

**Comment by wangfei0903** [comment]
I understand, thank you for your response

**Comment by wangfei0903** [comment]
Dear author, I have another question. Which image will be used as the guide image when calculating CLIPimage? Is it the original background image?

**Comment by Shilin-LU** [comment]
Hi, you may refer to this [issue](https://github.com/Shilin-LU/TF-ICON/issues/20) to see if it is clear. Thank you.

**Comment by wangfei0903** [comment]
Dear author, I understand how to calculate, but I have a question about how to process the results because after calculating the cosine similarity, the value is around 0.5 instead of 70 or 80. So I would like to ask you. In addition, when I chose to calculate CLIPimage, I used the fused image and background image for calculation.

**Comment by Shilin-LU** [comment]
> Dear author, I understand how to calculate, but I have a question about how to process the results because after calculating the cosine similarity, the value is around 0.5 instead of 70 or 80. So I would like to ask you. In addition, when I chose to calculate CLIPimage, I used the fused image and background image for calculation.


Please multiply the cosine similarity by 100 to obtain a percentage rather than a decimal. Additionally, the method used to calculate CLIPimage appears to be incorrect. Could you please follow the guidelines outlined in [Issue 20](https://github.com/Shilin-LU/TF-ICON/issues/20) for calculating the metrics accurately? Thank you for your attention to this matter.

The information is copied below for your convenience:

1. When calculating the LPIPS for the background, we mask out the foreground region (according to the user mask) on both the generated composition image and the provided foreground image, i.e., set those pixels to 0. Then calculate the LPIPS on masked images.

2. When it comes to the foreground, we crop the generated composition image (according to the user mask), and only compare the foreground image cropped out from the generated image with the provided reference image.

**Comment by wangfei0903** [comment]
Dear author, hello, thank you for your prompt response amidst your busy schedule. I have looked at issue 20 and calculated the LPIPS index according to the method you mentioned, but is the same method used to calculate CLIP? When calculating CLIPtext, I used fused images and prompt words to calculate image text correlation. However, when calculating image text correlation, I don't know which two images to use because there is only one image text correlation in the paper, and there is no distinction between foreground and background regions. I don't know if I have expressed my question clearly

**Comment by Shilin-LU** [comment]
> Dear author, hello, thank you for your prompt response amidst your busy schedule. I have looked at issue 20 and calculated the LPIPS index according to the method you mentioned, but is the same method used to calculate CLIP? When calculating CLIPtext, I used fused images and prompt words to calculate image text correlation. However, when calculating image text correlation, I don't know which two images to use because there is only one image text correlation in the paper, and there is no distinction between foreground and background regions. I don't know if I have expressed my question clearly

The CLIP_text is computed between the generated composite image and the text prompt. The CLIP_image is calculated between the cropped region of the generated image, according to the user’s mask, and the reference foreground image. I hope this clarifies things.

**Comment by wangfei0903** [comment]
I understand, thank you for your patient reply. Wishing you a happy life and smooth work
