### ISSUE TITLE
hello, what is the suggested params for same_domain?

### ISSUE THREAD

**Issue by ghost** [Shilin-LU/TF-ICON#5]
I find 0.4 0.8 works for cross_domain scenarios but not for same_domain.

**Comment by Shilin-LU** [comment]
Thanks for finding out the bug parameter 'cross_domain' here. 

We have updated a new version of the codebase that should be able to work well by simply setting the 'domain' parameter to 'same'.

For the old version, we should just remove the 'cross_domain' setting in our command, and then it will be set to False by default (rather than setting it to False manually, as in this case it will always be True, thus failing in 'same domain' mode)
